
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Sign In</title>
<link rel="stylesheet" href="CSS/deslog.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<html>    
<body>
    

    

    <p id="Wrong"> </p>
<div class="box">
<h2>Login</h2>
<form name="f" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post" > 
<div class="inputBox">
<input type="Email" name="Email" required="" value="<?= $_POST['Email'] ?? '' ?>">
<span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
<label><i class="fas fa-user" ></i> Username </label>
</div>
<div class="inputBox">
<input type="password" name="pwd" required="">
<label><i class="fas fa-lock"></i> Password</label>
<span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>
</div>
<input type="submit" name="LogIn"  value="Submit" >
<input type="reset" name="" value="Annuler" >
<div class="all">   
                        D'ont have a account ?<a href="SignUp.php" class="allready"> SignUp</a>
  </div>    
</form>
</div>
</body>
</html>
